In [33]:
import numpy as np 
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

In [34]:
reviews = [
    'nice food', 
    'amazing restaurant',
    'too good',
    'just love it!',
    'will do again',
    'horrible food',
    'never go there',
    'poor service',
    'poor quality',
    'needs improvements'
]

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [35]:
one_hot("amazing restaurant ever", 30) # (text, vocab_size) => give fix number for each word in dict

[24, 1, 15]

In [46]:
vocab_size = 50 
encoded_reviews = [one_hot(s, vocab_size) for s in reviews]
print(encoded_reviews)

[[18, 18], [7, 33], [29, 2], [32, 12, 34], [41, 9, 3], [39, 18], [22, 47, 13], [23, 29], [23, 16], [11, 6]]


In [37]:
max_length = 3 # for padding 
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[18 18  0]
 [ 7 33  0]
 [29  2  0]
 [32 12 34]
 [41  9  3]
 [39 18  0]
 [22 47 13]
 [23 29  0]
 [23 16  0]
 [11  6  0]]


In [38]:
embedded_vector_size = 4 # 4 features 

model = Sequential() 
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

c:\Users\HuyenDT\source\repos\sttproject\.venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [39]:
X = padded_reviews
y = sentiment

In [40]:
model.compile(
    optimizer = 'adam', 
    loss='binary_crossentropy',
    metrics=['accuracy']
)
model.build()
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_4 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [41]:
model.fit(X, y, epochs=50, verbose=0)

In [42]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - accuracy: 0.9000 - loss: 0.6176


0.8999999761581421

### Word embedding (side effect)

In [43]:
weights = model.get_layer("embedding").get_weights()[0]
weights

array([[ 0.02558825, -0.02812525, -0.04750338,  0.06588609],
       [-0.02615174, -0.04319992, -0.00913071,  0.01762016],
       [ 0.0942002 ,  0.09846929, -0.04051611, -0.05096036],
       [-0.05658365,  0.09032976,  0.08927005, -0.09842589],
       [ 0.04897405,  0.02547563,  0.01569996, -0.01120504],
       [ 0.02606433,  0.0466895 ,  0.00278004, -0.03467995],
       [-0.02753428, -0.09129338,  0.05437104,  0.04761848],
       [-0.05587698, -0.06965538,  0.03102339,  0.06875646],
       [-0.04911401,  0.03177531,  0.0373232 ,  0.00210339],
       [ 0.09489992,  0.06040489, -0.01056961, -0.06455317],
       [-0.01529082, -0.01317586,  0.04853321,  0.01482388],
       [ 0.01535131,  0.02255886, -0.08335668, -0.03014205],
       [ 0.08786507,  0.09217657, -0.00723706, -0.01440498],
       [ 0.0692312 , -0.00561486, -0.07593099,  0.07944558],
       [ 0.04808253,  0.02683207, -0.0236779 ,  0.0118984 ],
       [-0.01997963,  0.02714754,  0.03321962,  0.03565521],
       [-0.09649864, -0.

In [44]:
weights.shape

(50, 4)

In [ ]:
print(weights[18]) # nice
print(weights[7]) # amazing => similar words => similar weights

[-0.0525637  -0.05511295  0.05346769  0.03209735]
[-0.05587698 -0.06965538  0.03102339  0.06875646]
